filenameExtension="mkv";
filetype="matroska";
videocodec="libx265";         # always h265
audiocodec="aac";             # aac is alright
videobitrate="315k";
audiobitrate="256k";
preset="medium";
threads=0;                    #unlimited threads
width=480;
